openapi: 3.0.0
info:
  title: Power Assist API
  version: 1.0.0
paths:
  /repairs/{vehicleId}:
    get:
      summary: 수리 내역 조회
      parameters:
        - name: vehicleId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 수리 내역 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    troubleInfo:
                      type: string
                    repairDetail:
                      type: string
                    repairType:
                      type: string
                    billedAmount:
                      type: integer
                    requestedAmount:
                      type: integer
                    isAccident:
                      type: boolean
    post:
      summary: 수리 내역 추가
      parameters:
        - name: vehicleId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  troubleInfo:
                    type: string
                  repairDetail:
                    type: string
                  repairType:
                    type: string
                  billedAmount:
                    type: integer
                  requestedAmount:
                    type: integer
                  isAccident:
                    type: boolean
      responses:
        '200':
          description: 수리 내역 추가 성공
